name: PhpSpec (dependencies conflict)
on: push
jobs:
    phpspec:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: php-actions/composer@v6
                with:
                    args: --prefer-dist
                    php_version: '8.2'
            -   name: PHP Spec
                run: bin/phpspec run spec
